#include "pi_builtin.h"
#include "../pi_value.h"

BuiltinConst builtin_constants[] = {
    {"PI", {VAL_NUM, {.number = PI}}},
    {"E", {VAL_NUM, {.number = E}}},
    {"WIDTH", {VAL_NUM, {.number = SCREEN_WIDTH}}},
    {"HEIGHT", {VAL_NUM, {.number = SCREEN_HEIGHT}}},
    {"WAVE_SINE", {VAL_NUM, {.number = WAVE_SINE}}},
    {"WAVE_SQUARE", {VAL_NUM, {.number = WAVE_SQUARE}}},
    {"WAVE_TRIANGLE", {VAL_NUM, {.number = WAVE_TRIANGLE}}},
    {"WAVE_NOISE", {VAL_NUM, {.number = WAVE_NOISE}}},
    {"COLOR_SOFT_BLACK", {VAL_NUM, {.number = 0}}},
    {"COLOR_DEEP_BLUE", {VAL_NUM, {.number = 1}}},
    {"COLOR_DARK_MAGENTA", {VAL_NUM, {.number = 2}}},
    {"COLOR_DEEP_GREEN", {VAL_NUM, {.number = 3}}},
    {"COLOR_WARM_BROWN", {VAL_NUM, {.number = 4}}},
    {"COLOR_CHARCOAL_GRAY", {VAL_NUM, {.number = 5}}},
    {"COLOR_COOL_LIGHT_GRAY", {VAL_NUM, {.number = 6}}},
    {"COLOR_SOFT_IVORY", {VAL_NUM, {.number = 7}}},
    {"COLOR_VIVID_RED", {VAL_NUM, {.number = 8}}},
    {"COLOR_AMBER_ORANGE", {VAL_NUM, {.number = 9}}},
    {"COLOR_WARM_YELLOW", {VAL_NUM, {.number = 10}}},
    {"COLOR_NEON_GREEN", {VAL_NUM, {.number = 11}}},
    {"COLOR_SKY_BLUE", {VAL_NUM, {.number = 12}}},
    {"COLOR_DUSTY_PURPLE", {VAL_NUM, {.number = 13}}},
    {"COLOR_PINK_ROSE", {VAL_NUM, {.number = 14}}},
    {"COLOR_LIGHT_PEACH", {VAL_NUM, {.number = 15}}},
    {"COLOR_DARK_COCOA", {VAL_NUM, {.number = 16}}},
    {"COLOR_MIDNIGHT_BLUE", {VAL_NUM, {.number = 17}}},
    {"COLOR_PLUM", {VAL_NUM, {.number = 18}}},
    {"COLOR_OCEAN_TEAL", {VAL_NUM, {.number = 19}}},
    {"COLOR_BRICK_RED", {VAL_NUM, {.number = 20}}},
    {"COLOR_MUTED_MAUVE", {VAL_NUM, {.number = 21}}},
    {"COLOR_WARM_STONE", {VAL_NUM, {.number = 22}}},
    {"COLOR_PALE_YELLOW", {VAL_NUM, {.number = 23}}},
    {"COLOR_DEEP_PINK", {VAL_NUM, {.number = 24}}},
    {"COLOR_ORANGE_RED", {VAL_NUM, {.number = 25}}},
    {"COLOR_LIME_YELLOW", {VAL_NUM, {.number = 26}}},
    {"COLOR_EMERALD", {VAL_NUM, {.number = 27}}},
    {"COLOR_BRIGHT_COBALT", {VAL_NUM, {.number = 28}}},
    {"COLOR_DUSTY_VIOLET", {VAL_NUM, {.number = 29}}},
    {"COLOR_CORAL", {VAL_NUM, {.number = 30}}},
    {"COLOR_SOFT_SALMON", {VAL_NUM, {.number = 31}}},
    {"COLOR_GB_LIGHT_OLIVE", {VAL_NUM, {.number = 32}}},
    {"COLOR_GB_OLIVE", {VAL_NUM, {.number = 33}}},
    {"COLOR_GB_DARK_OLIVE", {VAL_NUM, {.number = 34}}},
    {"COLOR_GB_DEEP_OLIVE", {VAL_NUM, {.number = 35}}},
    {"COLOR_GB_INDIGO_GRAY", {VAL_NUM, {.number = 36}}},
    {"COLOR_GB_DESATURATED_CYAN", {VAL_NUM, {.number = 37}}},
    {"COLOR_GB_BRIGHT_LIME", {VAL_NUM, {.number = 38}}},
    {"COLOR_GB_PALE_MINT", {VAL_NUM, {.number = 39}}},
    {"COLOR_GB_ALMOST_BLACK", {VAL_NUM, {.number = 40}}},
    {"COLOR_GB_SLATE_GRAY", {VAL_NUM, {.number = 41}}},
    {"COLOR_GB_DUSTY_GRAY", {VAL_NUM, {.number = 42}}},
    {"COLOR_GB_SOFT_WHITE", {VAL_NUM, {.number = 43}}},
    {"COLOR_GB_MUTED_ROSE", {VAL_NUM, {.number = 44}}},
    {"COLOR_GB_SOFT_RED", {VAL_NUM, {.number = 45}}},
    {"COLOR_GB_APRICOT", {VAL_NUM, {.number = 46}}},
    {"COLOR_GB_CREAM", {VAL_NUM, {.number = 47}}},
    {"COLOR_NES_YELLOW_GREEN", {VAL_NUM, {.number = 48}}},
    {"COLOR_NES_GRASS_GREEN", {VAL_NUM, {.number = 49}}},
    {"COLOR_NES_MOSS_GREEN", {VAL_NUM, {.number = 50}}},
    {"COLOR_NES_DARK_EARTH", {VAL_NUM, {.number = 51}}},
    {"COLOR_NES_SAND", {VAL_NUM, {.number = 52}}},
    {"COLOR_NES_PUMPKIN", {VAL_NUM, {.number = 53}}},
    {"COLOR_NES_CLAY_RED", {VAL_NUM, {.number = 54}}},
    {"COLOR_NES_DARK_GOLD", {VAL_NUM, {.number = 55}}},
    {"COLOR_NES_FUCHSIA", {VAL_NUM, {.number = 56}}},
    {"COLOR_NES_BLOOD_RED", {VAL_NUM, {.number = 57}}},
    {"COLOR_NES_WHITE", {VAL_NUM, {.number = 58}}},
    {"COLOR_NES_PALE_LAVENDER", {VAL_NUM, {.number = 59}}},
    {"COLOR_NES_BLUE_GRAY", {VAL_NUM, {.number = 60}}},
    {"COLOR_NES_SKY_BLUE", {VAL_NUM, {.number = 61}}},
    {"COLOR_NES_ROYAL_BLUE", {VAL_NUM, {.number = 62}}},
    {"COLOR_NES_DARK_TEAL", {VAL_NUM, {.number = 63}}},
    {"COLOR_SEGA_DARK_BROWN", {VAL_NUM, {.number = 64}}},
    {"COLOR_SEGA_DEEP_RED", {VAL_NUM, {.number = 65}}},
    {"COLOR_SEGA_BRIGHT_RED", {VAL_NUM, {.number = 66}}},
    {"COLOR_SEGA_ORANGE", {VAL_NUM, {.number = 67}}},
    {"COLOR_SEGA_YELLOW", {VAL_NUM, {.number = 68}}},
    {"COLOR_SEGA_PURPLE", {VAL_NUM, {.number = 69}}},
    {"COLOR_SEGA_MAGENTA", {VAL_NUM, {.number = 70}}},
    {"COLOR_SEGA_VERY_DARK_BLUE", {VAL_NUM, {.number = 71}}},
    {"COLOR_SEGA_BLUE", {VAL_NUM, {.number = 72}}},
    {"COLOR_SEGA_LIGHT_BLUE", {VAL_NUM, {.number = 73}}},
    {"COLOR_SEGA_TEAL", {VAL_NUM, {.number = 74}}},
    {"COLOR_SEGA_GREEN", {VAL_NUM, {.number = 75}}},
    {"COLOR_SEGA_LIME", {VAL_NUM, {.number = 76}}},
    {"COLOR_SEGA_MUTED_RED_BROWN", {VAL_NUM, {.number = 77}}},
    {"COLOR_SEGA_LIGHT_ORANGE", {VAL_NUM, {.number = 78}}},
    {"COLOR_SEGA_LIGHT_LAVENDER_GRAY", {VAL_NUM, {.number = 79}}},
};
int BUILTIN_CONST_COUNT = sizeof(builtin_constants) / sizeof(BuiltinConst);

BuiltinFunc builtin_functions[] = {
    // Math
    {"floor", pi_floor},
    {"ceil", pi_ceil},
    {"round", pi_round},
    {"seed", pi_seed},
    {"rand", pi_rand},
    {"rand_n", pi_rand_n},
    {"sqrt", pi_sqrt},
    {"sin", pi_sin},
    {"cos", pi_cos},
    {"tan", pi_tan},
    {"asin", pi_asin},
    {"acos", pi_acos},
    {"atan", pi_atan},
    {"deg", pi_deg},
    {"rad", pi_rad},
    {"sum", pi_sum},
    {"exp", pi_exp},
    {"log2", pi_log2},
    {"log10", pi_log10},
    {"logE", pi_logE},
    {"pow", pi_pow},
    {"abs", pi_abs},
    {"mean", pi_mean},
    {"avg", pi_avg},
    {"var", pi_var},
    {"dev", pi_dev},
    {"median", pi_median},
    {"mode", pi_mode},
    {"max", pi_max},
    {"min", pi_min},

    // Graphics
    {"pixel", pi_pixel},
    {"line", pi_line},
    {"draw", pi_draw},
    {"clear", pi_clear},
    {"circ", pi_circ},
    {"rect", pi_rect},
    {"poly", pi_poly},
    {"color", pi_color},
    {"palette", pi_palette},
    {"sprite", pi_sprite},

    // Image
    {"image", pi_image},
    {"crop", pi_crop},
    {"resize", pi_resize},
    {"flip", pi_flip},
    {"rend2d", pi_rend2d},
    {"scale2d", pi_scale2d},
    {"tran2d", pi_tran2d},
    {"rot2d", pi_rotate2d},
    {"copy2d", pi_copy2d},

    // Time
    {"sleep", pi_sleep},
    {"time", _pi_time},

    // IO    
    {"println", pi_println},
    {"print", pi_print},
    {"printf", pi_printf},
    {"writeln", pi_writeln},
    {"key", pi_key},    
    {"typed", pi_typed},
    {"input", pi_input},

    // File
    {"open", pi_open},
    {"read", pi_read},
    {"write", pi_write},
    {"seek", pi_seek},
    {"close", pi_close},

    // String
    {"char", pi_char},
    {"ord", pi_ord},
    {"trim", pi_trim},
    {"upper", pi_upper},
    {"lower", pi_lower},
    {"replace", pi_replace},
    {"is_upper", pi_isUpper},
    {"is_lower", pi_isLower},
    {"is_digit", pi_isDigit},
    {"is_numeric", pi_isNumeric},
    {"is_alpha", pi_isAlpha},
    {"is_alnum", pi_isAlnum},
    {"split", pi_split},

    // Audio
    {"sound", pi_sound},
    {"melody", pi_melody},
    {"tone", pi_tone},
    {"play", pi_play},
    {"stop", pi_stop},
    {"pause", pi_pause},
    {"resume", pi_resume},
    {"is_playing", pi_isPlaying},
    {"channel", pi_channel},
    {"set_loop", pi_setLoop},

    // System
    {"fps", pi_fps},
    {"error", pi_error},
    {"zen", pi_zen},
    {"cursor", pi_cursor},
    {"mouse", pi_mouse},
    {"eval", pi_eval},
    {"run", pi_run},
    {"dis", pi_dis},


    // Type
    {"type", _pi_type},
    {"is_num", pi_isNum},
    {"is_str", pi_isStr},
    {"is_bool", pi_isBool},
    {"is_list", pi_isList},
    {"is_map", pi_isMap},
    {"as_num", pi_asNum},
    {"as_str", pi_asStr},
    {"as_bool", pi_asBool},

    // Collections
    {"push", pi_push},
    {"pop", pi_pop},
    {"peek", pi_peek},
    {"empty", pi_empty},
    {"sort", pi_sort},
    {"insert", pi_insert},
    {"unshift", pi_unshift},
    {"remove", pi_remove},
    {"append", pi_append},
    {"contains", pi_contains},
    {"index_of", pi_indexOf},
    {"reverse", pi_reverse},
    {"shuffle", pi_shuffle},
    {"copy", pi_copy},
    {"slice", pi_slice},
    {"len", pi_len},
    {"range", pi_range},

    // Functional
    {"map", _pi_map},
    {"filter", pi_filter},
    {"reduce", pi_reduce},
    {"find", pi_find},

    // Matrix
    {"size", pi_size},
    {"mult", pi_mult},
    {"dot", pi_dot},
    {"cross", pi_cross},
    {"eye", pi_eye},
    {"zeros", pi_zeros},
    {"ones", pi_ones},
    {"is_mat", pi_isMat},

    // Object
    {"clone", pi_clone},
    {"values", pi_values},
    {"keys", pi_keys},

    // 3D
    {"load3d", pi_load3d},
    {"rot3d", pi_rotate3d},
    {"tran3d", pi_translate3d},
    {"scale3d", pi_scale3d},
    {"proj3d", pi_project3d},
    {"rend3d", pi_render3d},
};

int BUILTIN_FUNC_COUNT = sizeof(builtin_functions) / sizeof(BuiltinFunc);
